name: Manual Deploy CDK - Stateful

on:
  workflow_dispatch:
    branches:
      - main
      - staging

jobs:
  deploy-to-staging:
    if: github.event.inputs.branch == 'staging'
    runs-on: ubuntu-latest
    env:
      STAGE: staging
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.STAGING_AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CDK Synthesize
        run: |
          npx aws-cdk synth \
            --app 'npx ts-node --prefer-ts-exts ./src/cdk/stateful/index.ts'
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: CDK Bootstrap
        run: |
          npx aws-cdk bootstrap \
            --app 'npx ts-node --prefer-ts-exts ./src/cdk/stateful/index.ts'
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: CDK Deploy
        run: |
          npx aws-cdk bootstrap \
            --app 'npx ts-node --prefer-ts-exts ./src/cdk/stateful/index.ts'
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

  deploy-to-production:
    if: github.event.inputs.branch == 'main'
    runs-on: ubuntu-latest
    env:
      STAGE: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.PROD_AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CDK Synthesize
        run: |
          npx aws-cdk synth \
            --app 'npx ts-node --prefer-ts-exts ./src/cdk/stateful/index.ts'
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: CDK Bootstrap
        run: |
          npx aws-cdk bootstrap \
            --app 'npx ts-node --prefer-ts-exts ./src/cdk/stateful/index.ts'
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: CDK Deploy
        run: |
          npx aws-cdk bootstrap \
            --app 'npx ts-node --prefer-ts-exts ./src/cdk/stateful/index.ts'
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
